name: Enable Auto-Merge for Exercism Bot

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review

jobs:
  enable-automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'exercism-solutions-syncer[bot]'

    # This grants the GITHUB_TOKEN write permissions for pull requests
    permissions:
      pull-requests: write
      contents: write
    # ----------------------

    steps:
      - name: Enable auto-merge for PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          # Using squash as we previously discussed for a clean history
          merge-method: squash
